openapi: "3.0.0"
info:
  version: 1.0.0
  title: Jours fériés en France
servers:
  - url: https://antoineaugusti.github.io/jours-feries-france-api/
paths:
  /{zone}.json:
    get:
      summary: Liste les jours fériés pour une zone, 20 ans dans le passé et 5 ans dans le futur
      parameters:
        - name: zone
          in: path
          description: Le nom de la zone
          required: true
          schema:
            $ref: '#/components/schemas/Zone'
      responses:
        200:
          description: Les jours fériés
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dates"
        404:
          description: La zone n'existe pas
  /{zone}/{annee}.json:
    get:
      summary: Liste les jours fériés pour une zone, pour une année
      parameters:
        - name: zone
          in: path
          description: Le nom de la zone
          required: true
          schema:
            $ref: '#/components/schemas/Zone'
        - name: annee
          in: path
          description: L'année pour les jours fériés
          required: true
          schema:
            type: integer
            example: 2020
      responses:
        200:
          description: Les jours fériés
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dates"
        404:
          description: "La zone n'existe ou l'année n'est pas disponible"
components:
  schemas:
    Dates:
      description: Les dates et noms des jours fériés. Les clés sont les dates en ISO 8601, les valeurs sont les noms des jours fériés.
      type: object
      additionalProperties:
        type: string
      example:
        "2025-01-01": "Jour de l'an"
        "2025-04-21": "Lundi de Pâques"
    Zone:
      type: string
      description: Nom des zones reconnues
      example: metropole
      enum:
        - alsace-moselle
        - guadeloupe
        - guyane
        - la-reunion
        - martinique
        - mayotte
        - metropole
        - nouvelle-caledonie
        - polynesie-francais
        - saint-barthelemy
        - saint-martin
        - saint-pierre-et-miquelon
        - wallis-et-futuna
